// ============================================================
// KEI — styles for KeiMasterApp
// ============================================================
import { StyleSheet } from 'react-native';
import { colors } from '../../utils/colors';
import { radius, fontSize, KEY_HEIGHT } from '../../utils/dimensions';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  flexFill: { flex: 1 },
  searchContainer: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 15, paddingTop: 10 },
  searchInput: { flex: 1, backgroundColor: colors.surface, color: colors.textOnPrimary, paddingHorizontal: 15, paddingVertical: 8, borderRadius: radius.md, fontSize: fontSize.md, borderWidth: 1, borderColor: colors.border },
  searchClearBtn: { marginLeft: -34, padding: 8 },
  searchClearText: { color: colors.textFaint, fontSize: fontSize.md, fontWeight: 'bold' },
  displayArea: { flex: 1, padding: 15 },
  headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  headerIndicator: { color: colors.primaryActive, fontSize: fontSize.sm, fontWeight: 'bold' },
  selIndicator: { color: colors.warning, fontSize: fontSize.sm, fontWeight: 'bold' },
  listView: { flex: 1, backgroundColor: colors.surface, borderRadius: radius.md, padding: 10 },
  emptyState: { flex: 1, backgroundColor: colors.surface, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center', padding: 20 },
  emptyStateText: { color: colors.textMuted, fontSize: fontSize.md, textAlign: 'center' },
  lineRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 4, borderBottomWidth: 0.5, borderBottomColor: colors.border },
  lineRowEditing: { backgroundColor: colors.editingHighlight, borderRadius: 6 },
  lineTapArea: { flex: 1, flexDirection: 'row' },
  lineNum: { color: colors.textMuted, fontSize: fontSize.sm, width: 35, fontWeight: 'bold' },
  lineText: { color: colors.text, fontSize: fontSize.lg, flex: 1 },
  lineDeleteBtn: { paddingHorizontal: 8, paddingVertical: 4 },
  lineDeleteText: { fontSize: fontSize.md },
  toggleMenuContainer: { paddingHorizontal: 15, paddingBottom: 8, flexDirection: 'row' },
  toggleBtn: { backgroundColor: colors.surfaceAlt, paddingHorizontal: 12, paddingVertical: 6, borderRadius: radius.lg, marginRight: 8 },
  sigilBtn: { backgroundColor: colors.accent },
  activeBtn: { borderWidth: 1, borderColor: colors.primaryActive },
  toggleBtnText: { color: colors.textOnPrimary, fontSize: fontSize.sm, fontWeight: 'bold' },
  advancedToolbar: { backgroundColor: '#020617', paddingVertical: 8, paddingHorizontal: 10, borderTopWidth: 1, borderColor: colors.border },
  cmdRowWrap: { flexDirection: 'row', flexWrap: 'wrap', marginBottom: 4 },
  cmdButton: { paddingHorizontal: 14, paddingVertical: 6, backgroundColor: colors.surface, borderRadius: radius.sm + 1, marginRight: 8, marginBottom: 6 },
  cmdText: { color: colors.primaryActive, fontSize: fontSize.md, fontWeight: 'bold' },
  toolbarNote: { color: colors.textMuted, fontSize: fontSize.xs, marginTop: 2 },
  sigilBoard: { backgroundColor: '#090d16', paddingVertical: 10, borderTopWidth: 1, borderColor: colors.accent },
  sigilHeader: { color: colors.textFaint, fontSize: fontSize.xs, textAlign: 'center', marginBottom: 8, letterSpacing: 1 },
  sigilScroll: { paddingHorizontal: 10 },
  sigilCard: { backgroundColor: colors.surface, borderRadius: radius.md, padding: 10, alignItems: 'center', marginRight: 10, width: 110, borderWidth: 1, borderColor: colors.border },
  sigilIcon: { fontSize: 26, marginBottom: 4 },
  sigilTitle: { color: colors.primaryActive, fontSize: 8, textAlign: 'center', fontWeight: 'bold' },
  keyboardContainer: { backgroundColor: colors.surface, paddingBottom: 10, paddingTop: 5, borderTopWidth: 1, borderColor: colors.border },
  langBar: { flexDirection: 'row', justifyContent: 'center', marginBottom: 6, alignItems: 'center', flexWrap: 'wrap' },
  langBtn: { paddingHorizontal: 12, paddingVertical: 4, backgroundColor: colors.surfaceAlt, borderRadius: radius.sm, marginHorizontal: 4, marginVertical: 2 },
  selBtn: { backgroundColor: colors.accentAlt },
  activeSel: { backgroundColor: colors.accentAltActive, borderWidth: 1, borderColor: '#fed7aa' },
  activeLang: { backgroundColor: colors.primary },
  langText: { color: colors.textOnPrimary, fontSize: fontSize.sm, fontWeight: 'bold' },
  keyRow: { flexDirection: 'row', justifyContent: 'center', marginBottom: 4, paddingHorizontal: 2 },
  keyRowWrap: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', marginBottom: 4, paddingHorizontal: 2 },
  key: { flex: 1, minWidth: 40, backgroundColor: colors.surfaceAlt, height: KEY_HEIGHT, justifyContent: 'center', alignItems: 'center', margin: 2, borderRadius: radius.sm },
  keyFixed: { height: KEY_HEIGHT, backgroundColor: colors.surfaceAlt, justifyContent: 'center', alignItems: 'center', margin: 2, borderRadius: radius.sm },
  modKey: { backgroundColor: colors.surfaceMuted },
  enterKey: { flex: 1, backgroundColor: colors.primary },
  spaceKey: { flex: 4 },
  keyText: { color: colors.textOnPrimary, fontSize: fontSize.lg, fontWeight: '600' },
  keyTextSmall: { color: colors.textOnPrimary, fontSize: 10, fontWeight: '700' },
  disabledText: { color: colors.textMuted },
  editingBanner: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: colors.editingHighlight, paddingHorizontal: 15, paddingVertical: 6, borderTopWidth: 1, borderColor: colors.border },
  editingBannerText: { color: colors.primaryActive, fontSize: fontSize.sm, fontWeight: 'bold' },
  editingBannerCancel: { color: colors.danger, fontSize: fontSize.sm, fontWeight: 'bold' },
  inputContainer: { flexDirection: 'row', padding: 10, backgroundColor: colors.background, borderTopWidth: 1, borderColor: colors.border },
  textInput: { flex: 1, backgroundColor: colors.surface, color: colors.textOnPrimary, paddingHorizontal: 15, paddingVertical: 10, borderRadius: radius.md, fontSize: fontSize.lg, maxHeight: 100 },
  addButton: { backgroundColor: colors.primary, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 18, borderRadius: radius.md, marginLeft: 8 },
  addText: { color: colors.textOnPrimary, fontWeight: 'bold', fontSize: fontSize.md },
});
